name: enough_icalendar
description: icalendar library in pure Dart. Fully compliant with RFC 5545.
version: 0.2.0
homepage: https://github.com/Enough-Software/enough_icalendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
